general:
  source: csv

  input1: F:\Projects\Pfizer_mCRPC\Data\pre_modelling\LRx_Dx_HCPHCos\01_total.csv
  output_dir: F:/Frederik/pfizer_mcrpc/pfizer_mcrpc/raw_data/QC/report

  date_cols: _DT
  count_cols: _CNT
  flag_cols: _FLAG
  freq_cols: _FREQ
  first_exp_date_cols: _MIN_DT
  last_exp_date_cols: _MAX_DT
  index_date_col: INDEX_DATE
  lookback_date_col: LOOKBACK_DATE
  gender_col: GENDER
  age_col: AGE_INDEX
  target_col: PN_FLAG
  patient_id_col: patient_id
  matched_patient_id_col: MATCHED_PATIENT_ID
  special_cols:
    - AGE_PC
  date_format: "%m/%d/%Y"

qcs:
# Relative date qcs made out of qc9
  - qc_num: qc9
    input_file: input1
    level: error
    qc_params:
      keys_columns_a:
        - first_exp_date_cols
        - last_exp_date_cols
      comparison: '>='
      key_column_b: lookback_date_col

  - qc_num: qc9
    input_file: input1
    level: error
    qc_params:
      keys_columns_a:
        - first_exp_date_cols
        - last_exp_date_cols
      comparison: '<'
      key_column_b: index_date_col

  - qc_num: qc1
    input_file: input1
    level: error

  - qc_num: qc3
    input_file: input1
    level: error

  - qc_num: qc4
    input_file: input1
    level: error

  - qc_num: qc6
    input_file: input1
    level: error

  - qc_num: qc7
    input_file: input1
    level: error

  - qc_num: qc8
    input_file: input1
    level: error

  - qc_num: qc11
    input_file: input1
    level: error
    qc_params:
      multiple_a_day: True

  - qc_num: qc12
    input_file: input1
    level: error

  - qc_num: qc13
    input_file: input1
    level: error

  - qc_num: qc14
    input_file: input1
    level: error

  - qc_num: qc15
    input_file: input1
    level: error

# A bunch of qc16s to get a feel for the distribution of bias between pos and neg
  - qc_num: qc16
    input_file: input1
    level: error
    qc_params:
      max_fraction_diff: 0.5

  - qc_num: qc16
    input_file: input1
    level: error
    qc_params:
      max_fraction_diff: 0.3

  - qc_num: qc16
    input_file: input1
    level: error
    qc_params:
      max_fraction_diff: 0.1

  - qc_num: qc16
    input_file: input1
    level: error
    qc_params:
      max_fraction_diff: 0.05

  - qc_num: qc16
    input_file: input1
    level: error
    qc_params:
      max_fraction_diff: 0.02

  - qc_num: qc18
    input_file: input1
    level: error

  - qc_num: qc19
    input_file: input1
    level: error
    qc_params:
      date_limit: 01/01/2014